title: 주간 업무 보고
labels: announcements
body:
  - type: markdown
    attributes:
      value: |
        ## 지난 주
        ### 찬준
        - [ ] 지난 주 업무 입력
        
        ### 나연
        - [ ] 지난 주 업무 입력
        
        ### 수민
        - [ ] 지난 주 업무 입력

        ### 재욱
        - [ ] 지난 주 업무 입력

        ## 이번 주
        ### 찬준
        - [ ] 지난 주 업무 입력
        
        ### 나연
        - [ ] 지난 주 업무 입력
        
        ### 수민
        - [ ] 이번 주 업무 입력

        ### 재욱
        - [ ] 이번 주 업무 입력