title: 주간 업무 보고 
labels: ["announcements"]
body:
  - type: markdown
    attributes:
      value: |
        ## 지난 주
        
  - type: textarea
    id: improvements
    attributes:
      label: 찬준
      description: "지난 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false

  - type: textarea
    id: improvements
    attributes:
      label: 나연
      description: "지난 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false
      
  - type: textarea
    id: improvements
    attributes:
      label: 수민
      description: "지난 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false
      
  - type: textarea
    id: improvements
    attributes:
      label: 재욱
      description: "지난 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 지난 주

  - type: textarea
    id: improvements
    attributes:
      label: 찬준
      description: "이번 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false

  - type: textarea
    id: improvements
    attributes:
      label: 나연
      description: "이번 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false
      
  - type: textarea
    id: improvements
    attributes:
      label: 수민
      description: "이번 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false
      
  - type: textarea
    id: improvements
    attributes:
      label: 재욱
      description: "이번 주 업무 입력"
      value: |
        - [ ] .
      render: markdown
    validations:
      required: false
